incent-config/Dangerfile
=> Add incent-config dangerfile

incent-config/Dangerfile
=> Handle empty program set in Dangerfile

gems/Dangerfile, services/Dangerfile
Create separate Dangerfiles for gems, services, and config repos.
Addresses #13
=> Segment Dangerfile for different types of repos

incent-config/Dangerfile
Add check for PR description to `incent-config-*` `Dangerfile`.
=> Add description check to incent-config Dangerfile

incent-config/Dangerfile
Raise an error and reject build if if rendering causes changes
Issue #24
=> Add rendered changes check

incent-config/Dangerfile
=> Revert "Add rendered changes check"

incent-config/Dangerfile
Raise an error and reject build if if rendering causes changes within the `./programs` directory
Issue #24
=> Add rendered changes of programs check

services/Dangerfile
Add `CHANGELOG` check within the `/services` directory.
=> Add CHANGELOG check to services

services/Dangerfile
Add logic and message for missing `CHANGELOG` here from https://github.com/technekes/danger/pull/34
=> Add changelog error message

incent-config/Dangerfile
Closes #36 #37
- Add danger check to validate that file changes match program-set in branch
- Add danger check to validate branch name
=> Add check for modified program set and branch name

incent-config/Dangerfile
Update error message for `program_set_mismatch?` and add `!` for underscore check as the branch check is an `unless` statement.
=> Update error message and underscore check

incent-config/Dangerfile
Add message for targeted-program-set and current directory
=> Add message

incent-config/Dangerfile
Add detailed error message and test `./targeted_program_set`
=> Add detailed error message

incent-config/Dangerfile
Fix danger error from ./targeted_program_set
=> Fix danger error

incent-config/Dangerfile
Optimize `incent-config/Dangerfile` by importing methods from `./Dangerfile`
=> Import methods from ./Dangerfile

incent-config/Dangerfile
Pass `program_set_mismatch?` validation if program-set in branch is `na`
=> Pass validation if program-set in branch is na

Dangerfile, gems/Dangerfile
Only check for changelog in gems
=> Only check for changelog in gems

services/Dangerfile
=> refactor: typo

incent-config/Dangerfile
=> PR title undefined bug

services/Dangerfile
Remove changelog check for services/Dangerfile
=> Remove changelog check

Dangerfile, gems/Dangerfile, incent-config/Dangerfile
Separate ZOHO and ADO ticket checks
=> Separate ZOHO and ADO ticket checks

Dangerfile, services/Dangerfile
Fail if incent/incent-config version bumps are build
=> Fail if incent/incent-config version bumps are build

services/Dangerfile
=> Fix parentheses

incent-config/Dangerfile
Allow for changes in the "shared" directory and a program-set directory to be committed and PRed on the same branch to alleviate friction and merge conflicts. 
AB#51514
=> Ignore shared changes

incent-config/Dangerfile
With the addition of the CUE mod (not being added and deleted upon validation) to the repository level, there is a need to ignore changes in this directory. 
[AB#54264](https://dev.azure.com/tkxs/TKXS%20PowerSuite/_workitems/edit/54264)
=> Ignore CUE mod changes

incent-config/Dangerfile
[AB#55629](https://dev.azure.com/tkxs/TKXS%20PowerSuite/_workitems/edit/55629/)
Include a list of files modified upon rendering.
=> Output rendered file changes
